"""schema base

Revision ID: e118b41669d2
Revises: 
Create Date: 2026-05-02 16:51:46.766174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e118b41669d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('subsetor', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('cotacoes_diarias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('abertura', sa.Float(), nullable=True),
    sa.Column('maxima', sa.Float(), nullable=True),
    sa.Column('minima', sa.Float(), nullable=True),
    sa.Column('fechamento', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'data', name='uq_cotacao_diaria')
    )
    op.create_table('fundamentos_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), nullable=False),
    sa.Column('fonte', sa.String(length=50), nullable=False),
    sa.Column('pl', sa.Float(), nullable=True),
    sa.Column('pvp', sa.Float(), nullable=True),
    sa.Column('dy', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roic', sa.Float(), nullable=True),
    sa.Column('margem_liquida', sa.Float(), nullable=True),
    sa.Column('margem_ebitda', sa.Float(), nullable=True),
    sa.Column('divida_liquida_ebitda', sa.Float(), nullable=True),
    sa.Column('liquidez_corrente', sa.Float(), nullable=True),
    sa.Column('cagr_receita_5a', sa.Float(), nullable=True),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('text_description', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'coletado_em', 'fonte', name='uq_snapshot')
    )
    op.create_table('relatorios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('gerado_em', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=True),
    sa.Column('score_geral', sa.Float(), nullable=True),
    sa.Column('score_qualidade', sa.Float(), nullable=True),
    sa.Column('score_valuation', sa.Float(), nullable=True),
    sa.Column('score_momento', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatorios')
    op.drop_table('fundamentos_snapshot')
    op.drop_table('cotacoes_diarias')
    op.drop_table('tickers')
    # ### end Alembic commands ###
